name: Deploy SynergeReader

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # runs on your self-hosted runner

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 1️⃣ Sync repository to target directory, preserving .env
      - name: Sync Repo to Target Directory
        run: |
          TARGET_DIR="/home/legal-read-2025/julian_test/repo"

          # Remove everything EXCEPT .env
          shopt -s extglob
          rm -rf $TARGET_DIR/!(".env")
          mkdir -p $TARGET_DIR
          rsync -av --exclude='.github' ./ $TARGET_DIR/

      # 2️⃣ Confirm files
      - name: Confirm Files
        run: ls -l /home/legal-read-2025/julian_test/repo

      # 3️⃣ Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          cd /home/legal-read-2025/julian_test/repo
          docker compose down         # stop old containers
          docker compose build        # rebuild images (frontend sees updated .env)
          docker compose up -d        # start fresh in background
