name: Push Repo to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # this runs directly on your server

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Sync Repo to Target Directory
        run: |
          TARGET_DIR="/home/legal-read-2025/julian_test/repo"

          # clean up and re-copy
          rm -rf $TARGET_DIR/*
          mkdir -p $TARGET_DIR
          rsync -av --exclude='.github' ./ $TARGET_DIR/

      - name: Confirm Files
        run: ls -l /home/legal-read-2025/julian_test/repo

      - name: Deploy with Docker Compose
        run: |
          cd /home/legal-read-2025/julian_test/repo
          docker compose down         # stop old containers
          docker compose build        # rebuild images
          docker compose up -d        # start fresh in background
