- name: Check Running User
  run: whoami

- name: Ensure Repo Directory
  run: |
    whoami
    TARGET_DIR="/home/legal-read-2025/repo"
    mkdir -p $TARGET_DIR
    rsync -av --exclude='.github' ./ $TARGET_DIR/
    whoami

- name: Build & Start Containers
  run: |
    whoami
    cd /home/legal-read-2025/repo
    docker-compose down
    docker-compose build --no-cache
    docker-compose up -d
    whoami
